export const CHAPTERS = {
    // Chapitres pour customisation des applications
    FILES: 2,
    MAILS: 6,
    MAIL_ANSWER: 15,
    RESTORE: 9,
    RESTORE_PARTIAL: 10,
    RESTORE_TOTAL: 11,
    PASSWORD: 12,
    PASSWORD_SUCCESS: 13,
    PASSWORD_ERROR: 14,
    TRASH: 16,
    IMAGES: 17,
    PASSWORD_FILE: 18,
    FILES_WITH_CHOICES: 19,
    CONTACTS: 20,
    USB_INSERTED: 22,
    GAME: 23,
    GAME_SUCCESS: 27,
    GAME_FAILURE: 28,
    FINAL: 29,
    WIN_MEMORY: 30,
    WIN_REBOOT: 31,
    FILES_ADDITIONAL: [17, 19, 24, 25, 26],
  };